import type { DocumentIR, DocumentOperation } from './document-agent';

/** Business arguments generated by the model. Runtime state never belongs here. */
export type CanonicalToolValue = string | number | boolean;
export type CanonicalToolArguments = Readonly<Record<string, CanonicalToolValue>>;
interface CanonicalToolFieldBase {
  readonly description?: string;
  readonly required?: boolean;
}
export type CanonicalToolField =
  | (CanonicalToolFieldBase & { readonly type: 'string'; readonly maxLength: number;
      readonly enum?: readonly string[]; readonly defaultValue?: string })
  | (CanonicalToolFieldBase & { readonly type: 'integer'; readonly minimum: number;
      readonly maximum: number; readonly defaultValue?: number })
  | (CanonicalToolFieldBase & { readonly type: 'boolean'; readonly defaultValue?: boolean });

/** The same declarative conditions are projected into JSON Schema and validation. */
export interface CanonicalToolInputCondition {
  readonly when: { readonly field: string; readonly values: readonly CanonicalToolValue[]; readonly includeAbsent?: boolean };
  readonly required?: readonly string[];
  readonly forbidden?: readonly string[];
}
export interface CanonicalToolInput {
  readonly type: 'object';
  readonly fields: Readonly<Record<string, CanonicalToolField>>;
  readonly additionalProperties: false;
  readonly conditions?: readonly CanonicalToolInputCondition[];
}

export type CanonicalToolTraceType = 'read_sources' | 'search' | 'analyze' | 'write_document' | 'render' | 'check' | 'publish' | 'patch';
interface CanonicalToolContractDefinition {
  readonly schemaVersion: 1;
  readonly toolId: string;
  readonly version: string;
  readonly description: string;
  /** Internal entries preserve legacy metadata; they cannot be advertised to a model. */
  readonly exposure: 'provider' | 'internal';
  readonly input: CanonicalToolInput;
  readonly preconditions: {
    readonly requiresExistingDocument: boolean;
    readonly requiresDocumentIR: boolean;
    readonly requiresWrite: boolean;
    readonly requiresRevision: boolean;
    readonly requiresAuthorization: boolean;
    readonly allowedOperations: readonly DocumentOperation[];
  };
  readonly effects: {
    readonly modifiesDocumentIR: boolean;
    readonly modifiesArtifact: boolean;
    readonly producesIRPatch: boolean;
    readonly producesObservation: boolean;
    readonly producesDiagnostics: boolean;
    readonly producesArtifactRefs: boolean;
  };
  readonly execution: {
    readonly cancellable: boolean;
    readonly timeoutMs: number;
    /** Local scheduling units, never provider prices. */
    readonly budgetUnits: number;
    readonly idempotency: {
      readonly mode: 'required' | 'optional' | 'none';
      readonly scope: 'task_call';
      readonly keyFields: readonly string[];
    };
  };
  readonly diagnostics: {
    readonly traceType: CanonicalToolTraceType;
    readonly failureCodes: readonly string[];
  };
}

const commonFailureCodes = [
  'invalid_tool_arguments', 'TOOL_PRECONDITION_FAILED', 'authorization_or_revision_invalid',
  'cancelled', 'tool_timeout', 'budget_exceeded', 'tool_failed', 'invalid_tool_result',
  'call_id_conflict', 'reconciliation_required', 'runtime_checkpoint_failed'
] as const;

function metadata(input: {
  readonly requiresWrite: boolean;
  readonly requiresExistingDocument: boolean;
  readonly budgetUnits: number;
  readonly traceType: CanonicalToolTraceType;
}): Omit<CanonicalToolContractDefinition, 'toolId' | 'description' | 'input' | 'exposure'> {
  return {
    schemaVersion: 1,
    version: '1.0',
    preconditions: {
      requiresExistingDocument: input.requiresExistingDocument,
      requiresDocumentIR: false,
      requiresWrite: input.requiresWrite,
      requiresRevision: input.requiresWrite && input.requiresExistingDocument,
      requiresAuthorization: true,
      allowedOperations: ['create', 'edit', 'analyze']
    },
    effects: {
      modifiesDocumentIR: false,
      modifiesArtifact: input.requiresWrite,
      producesIRPatch: false,
      producesObservation: true,
      producesDiagnostics: true,
      producesArtifactRefs: false
    },
    execution: {
      cancellable: true,
      timeoutMs: 60_000,
      budgetUnits: input.budgetUnits,
      idempotency: { mode: 'required', scope: 'task_call', keyFields: [] }
    },
    diagnostics: { traceType: input.traceType, failureCodes: commonFailureCodes }
  };
}

const internalInput: CanonicalToolInput = { type: 'object', fields: {}, additionalProperties: false };
/** Tool IDs, metadata and model arguments are authored only in this catalog. */
const canonicalToolCatalog = [
  {
    toolId: 'extract_source', description: 'Controlled extract_source operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: false, requiresExistingDocument: false, budgetUnits: 1, traceType: 'read_sources' })
  },
  {
    toolId: 'aggregate_data', description: 'Controlled aggregate_data operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: false, requiresExistingDocument: false, budgetUnits: 2, traceType: 'analyze' })
  },
  {
    toolId: 'generate_chart', description: 'Controlled generate_chart operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: true, requiresExistingDocument: false, budgetUnits: 3, traceType: 'write_document' })
  },
  {
    toolId: 'select_material', description: 'Controlled select_material operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: false, requiresExistingDocument: false, budgetUnits: 1, traceType: 'read_sources' })
  },
  {
    toolId: 'read_document_structure',
    description: 'Read the structure of the current document, or a one-based page or section. The runtime supplies the document.',
    exposure: 'provider',
    input: {
      type: 'object', additionalProperties: false,
      fields: {
        scope: { type: 'string', maxLength: 8, enum: ['document', 'page', 'section'], defaultValue: 'document' },
        ordinal: { type: 'integer', minimum: 1, maximum: 500 }
      },
      conditions: [
        { when: { field: 'scope', values: ['page', 'section'] }, required: ['ordinal'] },
        { when: { field: 'scope', values: ['document'], includeAbsent: true }, forbidden: ['ordinal'] }
      ]
    },
    ...metadata({ requiresWrite: false, requiresExistingDocument: true, budgetUnits: 1, traceType: 'read_sources' }),
    diagnostics: { traceType: 'read_sources', failureCodes: [...commonFailureCodes, 'page_scope_unavailable', 'target_not_found'] },
    preconditions: {
      requiresExistingDocument: true, requiresDocumentIR: true, requiresWrite: false,
      requiresRevision: true, requiresAuthorization: true, allowedOperations: ['create', 'edit', 'analyze']
    }
  },
  {
    toolId: 'apply_document_patch', description: 'Controlled apply_document_patch operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: true, requiresExistingDocument: true, budgetUnits: 4, traceType: 'patch' })
  },
  {
    toolId: 'render_preview', description: 'Controlled render_preview operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: false, requiresExistingDocument: false, budgetUnits: 2, traceType: 'render' })
  },
  {
    toolId: 'inspect_layout', description: 'Controlled inspect_layout operation', exposure: 'internal', input: internalInput,
    ...metadata({ requiresWrite: false, requiresExistingDocument: true, budgetUnits: 1, traceType: 'check' })
  }
] as const satisfies readonly CanonicalToolContractDefinition[];

export type CanonicalToolId = (typeof canonicalToolCatalog)[number]['toolId'];
export interface CanonicalToolContract extends CanonicalToolContractDefinition {
  readonly toolId: CanonicalToolId;
}
export type CanonicalToolRegistry = ReadonlyMap<CanonicalToolId, CanonicalToolContract>;

const frozenContracts: readonly CanonicalToolContract[] = deepFreeze(canonicalToolCatalog);
export const canonicalToolIds: readonly CanonicalToolId[] = Object.freeze(frozenContracts.map(contract => contract.toolId));

/** Each caller receives a new registry; catalog entries themselves are deeply immutable. */
export function createCanonicalToolRegistry(contracts: readonly CanonicalToolContract[] = frozenContracts): CanonicalToolRegistry {
  const entries = contracts.map(contract => {
    assertContract(contract);
    return [contract.toolId, deepFreeze(structuredClone(contract))] as const;
  });
  if (new Set(entries.map(([toolId]) => toolId)).size !== entries.length) throw new TypeError('tool_registry_invalid');
  return new Map(entries);
}

export interface ToolAuthorizationContext {
  readonly canRead: boolean;
  readonly canWrite: boolean;
  readonly allowedToolIds: readonly CanonicalToolId[];
}

/** Host-owned execution state. No part of this object is merged into Provider parameters. */
export interface ToolExecutionContext {
  readonly currentDocumentId?: string;
  readonly currentDocumentIR?: DocumentIR;
  readonly revision?: number;
  readonly operation: DocumentOperation;
  readonly capabilities: readonly CanonicalToolId[];
  readonly projectContext: { readonly projectId: string; readonly workId?: string };
  readonly authorization: ToolAuthorizationContext;
  readonly abortSignal: AbortSignal;
  readonly taskContext: {
    readonly taskId: string;
    /** Absolute host deadline in milliseconds. The model cannot extend task time. */
    readonly deadlineAt?: number;
    readonly checkpoint?: { readonly revision: number; readonly step: number };
  };
}

export interface AvailableToolContext extends Pick<ToolExecutionContext,
  'currentDocumentId' | 'currentDocumentIR' | 'revision' | 'operation' | 'capabilities' | 'authorization'> {
  readonly implementedToolIds: readonly CanonicalToolId[];
}

/** Registry membership is necessary but never sufficient to expose a tool. */
export function deriveAvailableToolSet(registry: CanonicalToolRegistry, context: AvailableToolContext): readonly CanonicalToolContract[] {
  return [...registry.values()].filter(contract => {
    const preconditions = contract.preconditions;
    if (contract.exposure !== 'provider' || !context.implementedToolIds.includes(contract.toolId) ||
        !context.capabilities.includes(contract.toolId) || !preconditions.allowedOperations.includes(context.operation)) return false;
    if (preconditions.requiresExistingDocument && !context.currentDocumentId?.trim()) return false;
    if (preconditions.requiresDocumentIR && !context.currentDocumentIR) return false;
    if (preconditions.requiresRevision && (!Number.isSafeInteger(context.revision) || Number(context.revision) < 0)) return false;
    if (preconditions.requiresWrite && !context.authorization.canWrite) return false;
    if (preconditions.requiresAuthorization && (!context.authorization.canRead || !context.authorization.allowedToolIds.includes(contract.toolId))) return false;
    return true;
  });
}

/** Projection only: required fields, defaults, enums and conditions remain in input. */
export function canonicalToolInputSchema(contract: CanonicalToolContract): Readonly<Record<string, unknown>> {
  assertContract(contract);
  const properties = Object.fromEntries(Object.entries(contract.input.fields).map(([key, field]) => [key, {
    type: field.type,
    ...(field.description === undefined ? {} : { description: field.description }),
    ...(field.type === 'string' ? { minLength: 1, maxLength: field.maxLength, ...(field.enum ? { enum: [...field.enum] } : {}) } : {}),
    ...(field.type === 'integer' ? { minimum: field.minimum, maximum: field.maximum } : {}),
    ...(field.defaultValue === undefined ? {} : { default: field.defaultValue })
  }]));
  const allOf = contract.input.conditions?.map(condition => ({
    if: {
      properties: { [condition.when.field]: { enum: [...condition.when.values] } },
      ...(condition.when.includeAbsent ? {} : { required: [condition.when.field] })
    },
    then: {
      ...(condition.required?.length ? { required: [...condition.required] } : {}),
      ...(condition.forbidden?.length ? { not: { anyOf: condition.forbidden.map(key => ({ required: [key] })) } } : {})
    }
  }));
  return {
    type: contract.input.type,
    additionalProperties: contract.input.additionalProperties,
    properties,
    required: Object.entries(contract.input.fields).filter(([, field]) => field.required).map(([key]) => key),
    ...(allOf?.length ? { allOf } : {})
  };
}

/** Closed-object validation; defaults and cross-field rules use the same contract. */
export function validateCanonicalToolArguments(contract: CanonicalToolContract, value: unknown): CanonicalToolArguments {
  if (!isRecord(value) || Object.keys(value).some(key => !Object.prototype.hasOwnProperty.call(contract.input.fields, key))) {
    throw new TypeError('invalid_tool_arguments');
  }
  const parsed: Record<string, CanonicalToolValue> = {};
  for (const [key, field] of Object.entries(contract.input.fields)) {
    if (field.required && !Object.prototype.hasOwnProperty.call(value, key)) throw new TypeError('invalid_tool_arguments');
    const raw = Object.prototype.hasOwnProperty.call(value, key) ? value[key] : field.defaultValue;
    if (raw === undefined) {
      if (field.required || Object.prototype.hasOwnProperty.call(value, key)) throw new TypeError('invalid_tool_arguments');
      continue;
    }
    if (field.type === 'string' && (typeof raw !== 'string' || !raw.trim() || raw.length > field.maxLength || (field.enum && !field.enum.includes(raw)))) throw new TypeError('invalid_tool_arguments');
    if (field.type === 'integer' && (!Number.isSafeInteger(raw) || Number(raw) < field.minimum || Number(raw) > field.maximum)) throw new TypeError('invalid_tool_arguments');
    if (field.type === 'boolean' && typeof raw !== 'boolean') throw new TypeError('invalid_tool_arguments');
    parsed[key] = raw as CanonicalToolValue;
  }
  for (const condition of contract.input.conditions ?? []) {
    const raw = parsed[condition.when.field];
    if (!(raw === undefined ? condition.when.includeAbsent : condition.when.values.includes(raw))) continue;
    if (condition.required?.some(key => parsed[key] === undefined) || condition.forbidden?.some(key => parsed[key] !== undefined)) {
      throw new TypeError('invalid_tool_arguments');
    }
  }
  return Object.freeze(parsed);
}

export interface DocumentToolDiagnostic {
  readonly code: string;
  readonly severity: 'info' | 'warning' | 'error';
  readonly message: string;
}
export interface DocumentToolArtifactRef {
  readonly kind: 'file' | 'work' | 'preview';
  readonly ref: string;
}
interface DocumentToolResultData {
  readonly schemaVersion: 1;
  readonly observation?: Readonly<Record<string, unknown>>;
  /** Reserved for a later Application patch validator; no current provider tool produces it. */
  readonly irPatch?: Readonly<Record<string, unknown>>;
  readonly diagnostics?: readonly DocumentToolDiagnostic[];
  readonly artifactRefs?: readonly DocumentToolArtifactRef[];
  readonly metadata?: Readonly<Record<string, CanonicalToolValue>>;
}
export type DocumentToolResult = DocumentToolResultData & (
  | { readonly status: 'success' }
  | { readonly status: 'failed' }
  | { readonly status: 'cancelled' }
  | { readonly status: 'unknown' }
);

/** Validate the result envelope before Application commits or projects any tool output. */
export function validateDocumentToolResult(contract: CanonicalToolContract, value: unknown): DocumentToolResult {
  if (!isRecord(value) || value.schemaVersion !== 1 || !['success', 'failed', 'cancelled', 'unknown'].includes(String(value.status)) ||
      Object.keys(value).some(key => !['schemaVersion', 'status', 'observation', 'irPatch', 'diagnostics', 'artifactRefs', 'metadata'].includes(key))) {
    throw new TypeError('invalid_tool_result');
  }
  // Patch execution/commit is intentionally unavailable in this migration batch.
  if (value.irPatch !== undefined) throw new TypeError('invalid_tool_result');
  if (value.observation !== undefined && (!contract.effects.producesObservation || !isRecord(value.observation))) throw new TypeError('invalid_tool_result');
  if (value.diagnostics !== undefined && (!contract.effects.producesDiagnostics || !Array.isArray(value.diagnostics) || value.diagnostics.length > 64 ||
      value.diagnostics.some(item => !isRecord(item) || Object.keys(item).some(key => !['code', 'severity', 'message'].includes(key)) ||
        typeof item.code !== 'string' || !/^[A-Za-z][A-Za-z0-9_.-]{0,127}$/.test(item.code) ||
        (item.severity === 'error' && !contract.diagnostics.failureCodes.includes(item.code)) ||
        !['info', 'warning', 'error'].includes(String(item.severity)) || typeof item.message !== 'string' || item.message.length > 2_000))) {
    throw new TypeError('invalid_tool_result');
  }
  if (value.artifactRefs !== undefined && (!contract.effects.producesArtifactRefs || !Array.isArray(value.artifactRefs) || value.artifactRefs.length > 64 ||
      value.artifactRefs.some(item => !isRecord(item) || Object.keys(item).some(key => !['kind', 'ref'].includes(key)) ||
        !['file', 'work', 'preview'].includes(String(item.kind)) || typeof item.ref !== 'string' || !/^[A-Za-z0-9_.:-]{1,128}$/.test(item.ref)))) {
    throw new TypeError('invalid_tool_result');
  }
  if (value.metadata !== undefined && (!isRecord(value.metadata) || Object.values(value.metadata).some(item =>
    typeof item !== 'string' && typeof item !== 'boolean' && !(typeof item === 'number' && Number.isFinite(item))))) throw new TypeError('invalid_tool_result');
  assertJsonValue(value, 0, { count: 0 });
  return value as unknown as DocumentToolResult;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && Object.getPrototypeOf(value) === Object.prototype;
}
function assertContract(contract: CanonicalToolContract): void {
  if (!canonicalToolIds.includes(contract.toolId) || contract.schemaVersion !== 1 ||
      !contract.version.trim() || !contract.description.trim() || !['provider', 'internal'].includes(contract.exposure) ||
      contract.input.type !== 'object' || contract.input.additionalProperties !== false ||
      !Number.isSafeInteger(contract.execution.timeoutMs) || contract.execution.timeoutMs < 1 || contract.execution.timeoutMs > 900_000 ||
      !Number.isSafeInteger(contract.execution.budgetUnits) || contract.execution.budgetUnits < 1 || contract.execution.budgetUnits > 10_000) {
    throw new TypeError('tool_schema_invalid');
  }
  const fields = contract.input.fields;
  const entries = Object.entries(fields);
  if (entries.length > 32) throw new TypeError('tool_schema_invalid');
  const reservedNames = ['reason', '__proto__', 'constructor', 'prototype', 'documentRef', 'documentId', 'currentDocumentId',
    'currentDocumentIR', 'revision', 'authorization', 'abortSignal', 'signal', 'taskContext', 'checkpoint', 'projectContext',
    'filePath', 'path', 'rootDirectory', 'relativePath'];
  for (const [key, field] of entries) {
    if (!/^[a-zA-Z][a-zA-Z0-9_]{0,63}$/.test(key) || reservedNames.includes(key) ||
        (field.required !== undefined && typeof field.required !== 'boolean')) throw new TypeError('tool_schema_invalid');
    if (field.type === 'string') {
      if (!Number.isSafeInteger(field.maxLength) || field.maxLength < 1 || field.maxLength > 2_000 ||
          (field.enum && (!field.enum.length || field.enum.length > 64 || field.enum.some(item => !item.trim() || item.length > field.maxLength))) ||
          (field.defaultValue !== undefined && (typeof field.defaultValue !== 'string' || !field.defaultValue.trim() || field.defaultValue.length > field.maxLength ||
            (field.enum && !field.enum.includes(field.defaultValue))))) throw new TypeError('tool_schema_invalid');
    } else if (field.type === 'integer') {
      if (!Number.isSafeInteger(field.minimum) || !Number.isSafeInteger(field.maximum) || field.minimum > field.maximum ||
          (field.defaultValue !== undefined && (!Number.isSafeInteger(field.defaultValue) || field.defaultValue < field.minimum || field.defaultValue > field.maximum))) throw new TypeError('tool_schema_invalid');
    } else if (field.type === 'boolean') {
      if (field.defaultValue !== undefined && typeof field.defaultValue !== 'boolean') throw new TypeError('tool_schema_invalid');
    } else throw new TypeError('tool_schema_invalid');
  }
  for (const condition of contract.input.conditions ?? []) {
    if (!Object.prototype.hasOwnProperty.call(fields, condition.when.field) || !condition.when.values.length ||
        [...condition.required ?? [], ...condition.forbidden ?? []].some(key => !Object.prototype.hasOwnProperty.call(fields, key))) throw new TypeError('tool_schema_invalid');
  }
  if (contract.execution.idempotency.keyFields.some(key => !Object.prototype.hasOwnProperty.call(fields, key))) throw new TypeError('tool_schema_invalid');
}
function assertJsonValue(value: unknown, depth: number, state: { count: number }): void {
  if (depth > 8 || ++state.count > 4_096) throw new TypeError('invalid_tool_result');
  if (value === null || typeof value === 'boolean') return;
  if (typeof value === 'number' && Number.isFinite(value)) return;
  if (typeof value === 'string' && value.length <= 8_000) return;
  if (Array.isArray(value) && value.length <= 128) {
    value.forEach(item => assertJsonValue(item, depth + 1, state));
    return;
  }
  if (isRecord(value) && Object.keys(value).length <= 64 && !Object.keys(value).some(key => ['__proto__', 'constructor', 'prototype'].includes(key))) {
    Object.values(value).forEach(item => assertJsonValue(item, depth + 1, state));
    return;
  }
  throw new TypeError('invalid_tool_result');
}
function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(deepFreeze);
    Object.freeze(value);
  }
  return value;
}
